version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-website
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
